---
# all variables here are accesible in the template under the 'branchVars' variable
# so for example redis.port becomes branchVars.redis.port

redis:     
   port: 6379
   skipConfigCreation: true

lan:
    vm_ip: 192.168.0.100
   
java:
   startupMemory: 512M
   maxMemory: 1G
   additionalStartupParams:
   executable: /usr/lib/jvm/temurin-17-jdk-amd64/bin/java
   
domains:   
   main: jidelnicek.aperto.cz
   ssl: jidelnicek.aperto.cz
   files: files.jidelnicek.aperto.cz
   imagesProxy: images.jidelnicek.aperto.cz
   
filesFolder: cz.aperto.jidelnicek

nginx:
   cacheIdentifier: ApertoFoodlistCache